# THEME SOURCE: https://github.com/526avijitgupta/gokarna

baseURL = "https://cosior.github.io/"
title = "Costas Iordanou"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Costas Iordanou"
  description = "Assistant Professor in Network Security @ European University Cyprus"
  avatarURL = "/images/costas_iordanou_p.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-xl"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XPZCHJSW1Z"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-XPZCHJSW1Z');
    </script>

    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/costas-iordanou-4447a278/", title=""},
    {name = "facebook", url = "https://www.facebook.com/cos.ior.7"},
    {name = "youtube", url = "https://www.youtube.com/channel/UC3jzlFkM439sGheIyNATY4w"},
    {name = "googlescholar", url = "https://scholar.google.com/citations?hl=en&user=Nxo-Yp8AAAAJ"},
    #{name = "dribbble", url = "https://example.com"},
    #{name = "instagram", url = "https://example.com"},
    #{name = "twitch", url = "https://example.com"},
    {name = "email", url = "mailto:C.Iordanou@euc.ac.cy"}
  ]
  metaKeywords = ["blog", "Research", "Costas Iordanou", "Costas", "Iordanou", "Professor", "network", "security", "european", "university", "cyprus"]

# Images source website: https://feathericons.com/
[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book-open'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    pre = "<span data-feather='archive'></span>"
    url = "/publications"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='grid'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "googlescholar"
    pre = "<span data-feather='book'></span>"
    url = "https://scholar.google.com/citations?hl=en&user=Nxo-Yp8AAAAJ"
    weight = 6

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/costas-iordanou-4447a278/"
    weight = 7

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/cosior"
    weight = 8

  #[[menu.main]]
  #  identifier = "buymeacoffee"
  #  pre = "<span data-feather='coffee'></span>"
  #  url = "https://www.buymeacoffee.com/avijitgupta"
  #  weight = 9

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 10

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
